#logging:
#  level:
#    org:
#      springframework:
#        cache: DEBUG
application:
  title: Church CRM
  version: 1.0.0
server:
  port: 8080
#  tomcat:
#    uri-encoding: ISO_8859_1
#  servlet:
#    encoding:
#      charset: ISO_8859_1
#      force: true
spring:
  datasource:
    url: jdbc:h2:mem:church-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  messages:
    basename: i18n/messages
#    encoding: ISO_8859_1
  main:
    allow-bean-definition-overriding: true
